const products = [
    {
      id: 1,
      title: 'ravioles con salsa',
      company: 'comidas',
      image:'./images/plato1.jpg',
      price: 9.99,
    },
    {
      id:2,
      title:'paella de mariscos',
      company:'comidas',
      image:'./images/plato2.jpg',
      price:15.00,
    },
    {
      id:3,
      title:'lasaña clasica',
      company:'comidas',
      image:'./images/plato3.jpg',
      price:5.00,
    },
    {
      id:4,
      title:'lasaña clasica',
      company:'comidas',
      image:'./images/plato3.jpg',
      price:5.00,
    },
    {
      id:5,
      title:'paella de mariscos',
      company:'comidas',
      image:'./images/plato2.jpg',
      price:15.00,
    },
    {
      id:6,
      title:'paella de mariscos',
      company:'comidas',
      image:'./images/plato2.jpg',
      price:15.00,
    },
    {
      id: 7,
      title: 'ravioles con salsa',
      company: 'comidas',
      image:'./images/plato1.jpg',
      price: 9.99,
    },
    {
      id: 8,
      title: 'ravioles con salsa',
      company: 'comidas',
      image:'./images/plato1.jpg',
      price: 9.99,
    },
    {
      id: 9,
      title: 'ravioles con salsa',
      company: 'comidas',
      image:'./images/plato1.jpg',
      price: 9.99,
    },
    {
      id: 10,
      title: 'ravioles con salsa',
      company: 'postres',
      image:'./images/plato1.jpg',
      price: 9.99,
    },
    {
      id: 11,
      title: 'ravioles con salsa',
      company: 'postres',
      image:'./images/plato1.jpg',
      price: 9.99,
    },
    {
      id: 12,
      title: 'ravioles con salsa',
      company: 'postres',
      image:'./images/plato1.jpg',
      price: 9.99,
    },
    {
      id: 13,
      title: 'ravioles con salsa',
      company: 'postres',
      image:'./images/plato1.jpg',
      price: 9.99,
    },
    {
      id: 14,
      title: 'ravioles con salsa',
      company: 'postres',
      image:'./images/plato1.jpg',
      price: 9.99,
    },
    {
      id: 15,
      title: 'ravioles con salsa',
      company: 'postres',
      image:'./images/plato1.jpg',
      price: 9.99,
    },
    {
      id: 16,
      title: 'ravioles con salsa',
      company: 'postres',
      image:'./images/plato1.jpg',
      price: 9.99,
    },
    {
      id: 17,
      title: 'ravioles con salsa',
      company: 'bebidas',
      image:'./images/plato1.jpg',
      price: 9.99,
    },
    {
      id: 18,
      title: 'ravioles con salsa',
      company: 'postres',
      image:'./images/plato1.jpg',
      price: 9.99,
    },
    {
      id: 19,
      title: 'ravioles con salsa',
      company: 'postres',
      image:'./images/plato1.jpg',
      price: 9.99,
    },
    {
      id: 20,
      title: 'ravioles con salsa',
      company: 'postres',
      image:'./images/plato1.jpg',
      price: 9.99,
    },
    {
      id: 21,
      title: 'ravioles con salsa',
      company: 'postres',
      image:'./images/plato1.jpg',
      price: 9.99,
    },
    {
      id: 22,
      title: 'ravioles con salsa',
      company: 'postres',
      image:'./images/plato1.jpg',
      price: 9.99,
    },
    {
      id: 23,
      title: 'ravioles con salsa',
      company: 'postres',
      image:'./images/plato1.jpg',
      price: 9.99,
    },
    {
      id: 24,
      title: 'ravioles con salsa',
      company: 'postres',
      image:'./images/plato1.jpg',
      price: 9.99,
    },
    {
      id: 25,
      title: 'ravioles con salsa',
      company: 'postres',
      image:'./images/plato1.jpg',
      price: 9.99,
    },
    {
      id: 26,
      title: 'ravioles con salsa',
      company: 'postres',
      image:'./images/plato1.jpg',
      price: 9.99,
    },
    {
      id: 27,
      title: 'ravioles con salsa',
      company: '',
      image:'./images/plato1.jpg',
      price: 9.99,
    },
    {
      id: 28,
      title: 'ravioles con salsa',
      company: '',
      image:'./images/plato1.jpg',
      price: 9.99,
    },
    {
      id: 29,
      title: 'ravioles con salsa',
      company: '',
      image:'./images/plato1.jpg',
      price: 9.99,
    },
    {
      id: 30,
      title: 'ravioles con salsa',
      company: '',
      image:'./images/plato1.jpg',
      price: 9.99,
    },
    {
      id: 31,
      title: 'ravioles con salsa',
      company: '',
      image:'./images/plato1.jpg',
      price: 9.99,
    },
    {
      id: 32,
      title: 'ravioles con salsa',
      company: '',
      image:'./images/plato1.jpg',
      price: 9.99,
    },
    {
      id: 33,
      title: 'ravioles con salsa',
      company: '',
      image:'./images/plato1.jpg',
      price: 9.99,
    },
    {
      id: 34,
      title: 'ravioles con salsa',
      company: '',
      image:'./images/plato1.jpg',
      price: 9.99,
    },
    {
      id: 35,
      title: 'ravioles con salsa',
      company: '',
      image:'./images/plato1.jpg',
      price: 9.99,
    }
  ];
  